name: Update Repository

on:
  [push]
  # and trigger manually
  # schedule:
  #   - cron: "0 23 1 * *"

defaults:
  run:
    shell: bash

permissions:
  contents: write

jobs:
  update_repo:
    name: update_repo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup R # this takes 38 seconds
        uses: r-lib/actions/setup-r@v2
      - name: Install system dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::kofdata
      - name: Run Rscript
        run: |
          Rscript R/import_data.R
      - name: Commit and push changes
        run: |
          git config --global user.name "${{ secrets.GH_ACTOR }}"
          git config --global user.email "${{ secrets.GH_ACTOR }}@users.noreply.github.com"
          git add -A
          git commit -m "Automated Update of Datasets in Repo"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
