name: Update Repository

on:
  [push]
  # and trigger manually
  # schedule:
  #   - cron: "0 23 1 * *"

defaults:
  run:
    shell: bash

permissions:
  contents: write

jobs:
  update_repo:
    name: update_repo
    runs-on: ubuntu-22.04
    container: rocker/verse:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: kofdata
      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ~/.R
          key: ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION') }}
          restore-keys: |
            ${{ runner.os }}-r-

      - name: Install R Packages
        run: |
          R -e 'if (!requireNamespace("kofdata", quietly = TRUE)) install.packages("kofdata")'
      - name: Run Rscript
        run: |
          Rscript R/import_data.R
      - name: Commit and push changes
        run: |
          git config --global --add safe.directory /__w/data/data
          git config --global user.name "${{ secrets.GH_ACTOR }}"
          git config --global user.email "${{ secrets.GH_ACTOR }}@users.noreply.github.com"
          git add -A
          if ! git diff --staged --quiet; then
            git commit -m "Automated Update of Datasets in Repo"
            git push
          fi

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
